# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
    - targets: ['10.255.31.20:7070']
    - targets: ['10.255.31.21:7070']
    - targets: ['10.255.31.22:7070']
    - targets: ['10.255.31.23:7070']
    - targets: ['10.255.31.24:7070']
    - targets: ['10.255.32.20:7070']
    - targets: ['10.255.32.21:7070']
    - targets: ['10.255.32.22:7070']
    - targets: ['10.255.32.23:7070']
    - targets: ['10.255.32.24:7070']

