{
 "title": "Cassandra - Cluster View",
 "description": "Monitoring Cassandra with Prometheus using JXM exporter",
 "tags": [ "cassandra" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "10.206.31.20:7070,10.206.31.21:7070,10.206.31.22:7070,10.206.31.23:7070,10.206.31.24:7070"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" },
   { "name": "node0", "query": "${VAR_NODE0}" },
   { "name": "node1", "query": "${VAR_NODE1}" },
   { "name": "node2", "query": "${VAR_NODE2}" },
   { "name": "node3", "query": "${VAR_NODE3}" },
   { "name": "node4", "query": "${VAR_NODE4}" }
  ]
 },
 "panels": [
  { "title": "Ring Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$node0\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$node1\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$node2\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$node3\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$node4\"}"
    }
   ]
  },
  { "title": "DIsk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Top10 tables by size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(cassandra_columnfamily_totaldiskspaceused{keyspace=~\".+\",instance=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Total disk usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_load{instance=~\"$instance\"}",
     "legendFormat": "Total disk usage:{{instance}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Top10 SSTables count $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,cassandra_columnfamily_livesstablecount{keyspace=~\".+\",instance=~\"$instance\"}) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Pending tasks count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{instance=~\"$instance\"}",
     "legendFormat": "Pending tasks:{{instance}}"
    }
   ]
  },
  {
   "title": "Completed tasks count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_completedtasks{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Completed tasks:{{instance}}"
    }
   ]
  },
  {
   "title": "Completed compactions $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_totalcompactionscompleted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Compactions completed"
    }
   ]
  },
  {
   "title": "SSTablesPerRead $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_sstablesperreadhistogram{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes compacted $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_bytescompacted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Bytes compacted"
    }
   ]
  },
  { "title": "Bloom filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "False positives $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalsepositives{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}{{instance}}"
    }
   ]
  },
  {
   "title": "False ratio $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalseratio{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}{{instance}}"
    }
   ]
  },
  {
   "title": "Disk usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterdiskspaceused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}:{{instance}}"
    }
   ]
  },
  {
   "title": "OffHeap memory used $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilteroffheapmemoryused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}:{{instance}}"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Completed tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_threadpools_completedtasks{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{threadpools}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Active tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_activetasks{instance=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}:{{instance}}"
    }
   ]
  },
  { "title": "Memtables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total memtables size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtableonheapsize{keyspace=\"\",instance=~\"$instance\"}",
     "legendFormat": "OnHeap:{{instance}}"
    },
    {
     "expr": "sum(cassandra_columnfamily_memtableoffheapsize{keyspace=\"\",instance=~\"$instance\"})",
     "legendFormat": "OffHeap:{{instance}}"
    }
   ]
  },
  {
   "title": "Memtables columns count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtablecolumnscount{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Memtables switch count / sec $instance",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_memtableswitchcount{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}:{{instance}}"
    }
   ]
  },
  { "title": "CQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "CQL regular statements / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cql_regularstatementsexecuted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Regular statements"
    }
   ]
  },
  {
   "title": "CQL prepared statements $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cql_preparedstatementsexecuted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Prepared statements"
    }
   ]
  }
 ]
}